name: buy_buddy_user_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  get_it: ^8.0.3
  dartz: ^0.10.1
  flutter_bloc: ^9.1.0
  device_preview: ^1.2.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.3
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  path_provider: ^2.1.5 
  easy_localization: ^3.0.8
  google_fonts: ^6.3.1
  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/translations/


# flutter_assets:
#   assets_path: assets/svgs
#   output_path: lib/core/utils
#   filename: app_svgs.dart
#   field_prefix: null
#   classname: AppSvgs

# flutter_assets:
#   assets_path: assets/images
#   output_path: lib/core/utils
#   filename: app_images.dart
#   field_prefix: null
#   classname: AppImages

# flutter_assets:
#   assets_path: assets/animations
#   output_path: lib/core/utils
#   filename: app_animations.dart
#   field_prefix: null
#   classname: AppAnimations    